<?xml version="1.0" encoding="utf-8"?><Database Name="e-Shop" Class="DataClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-ANAR\SQLEXPRESS;Initial Catalog=e-Shop;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="e_ShopConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="ProductPrice" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="ProductDiscount" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="ProductInfo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ProductCategoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductView" Member="ProductViews">
    <Type Name="ProductView">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="ProductPrice" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="ProductDiscount" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="ProductInfo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(64)" CanBeNull="true" />
    </Type>
  </Table>
</Database>